#! /bin/bash

source /home/core/.bashrc
mount_data

sudo systemctl start etcd
sudo systemctl start fleet

while [ 1 ]
do
    #git update docker
    cd /home/core/docker/
    sudo git pull
    sleep 600s

    # #rsync the data to server data
    # if [ DIR_SMB_RSYNC_FROM != "" ]
    # then
    #     rsync -vrI DIR_SMB_RSYNC_FROM DIR_SMB_RSYNC_TO
    # fi
done
