#! /bin/bash

sudo touch /home/core/.profile
source /home/core/.profile
/home/core/docker/shell/mount_data

sudo systemctl start etcd
sudo systemctl start fleet

i=1

while [ 1 ]
do
    #git update docker
    cd /home/core/docker/
    sudo git pull origin master

    /home/core/docker/shell/autorun_git

    if [ "${SSH_CONFIG}" != "" ]
    then
        /home/core/docker/shell/ssh_config ${SSH_CONFIG}
    fi    

    sleep 600s

    let x=i%30
    let i+=1

    if [ $x = 0 ]
    then
        for SERVICE_NAME in redis mysql php nginx
        do
            docker pull ivories/$SERVICE_NAME:1.0

            docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker stop
            docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker rm
            docker images|grep none|awk '{print $3 }'|xargs docker rmi
        done
    fi

    # #rsync the data to server data
    # if [ DIR_SMB_RSYNC_FROM != "" ]
    # then
    #     rsync -vrI DIR_SMB_RSYNC_FROM DIR_SMB_RSYNC_TO
    # fi
done
