#!/bin/bash
docker stop spark && docker rm spark
docker run -it --rm --name spark --security-opt seccomp=unconfined -v /home/core/data:/data -v /home/core/data/spark:/usr/local/hadoop-2.6.0/etc/hadoop/spark -h sandbox ivories/bowtie:1.0 bash
