#!/bin/bash

#docker run --rm -e USER=root --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/rust -w /usr/src/rust ivories/rust cargo $*

docker run --rm -it -e "TERM=xterm-256color" -e USER=root --user "root":"root" -v /home/core/data/rust/cargo:/root/.cargo -v "$PWD":/usr/src/rust -w /usr/src/rust ivories/rust cargo $*
