#!/bin/bash

docker stop cargo 1>/dev/null 2>/dev/null
docker rm cargo 1>/dev/null 2>/dev/null

docker run --name cargo -it -e "RUSTUP_DIST_SERVER=http://mirrors.ustc.edu.cn/rust-static" -e "RUSTUP_UPDATE_ROOT=http://mirrors.ustc.edu.cn/rust-static/rustup" -e "TERM=xterm-256color" --net=host -e USER=root --user "root":"root" -v /home/core/data/rust/cargo:/root/.cargo -v "$PWD":/data/rust -w /data/rust ivories/rust cargo $*

docker stop cargo 1>/dev/null 2>/dev/null
docker rm cargo 1>/dev/null 2>/dev/null

