#! /bin/bash

#docker images |awk -F "[ ]{2,}"  '{ printf "%32.32s    %16.16s    %16.16s    %16.16s    %16.16s    %8.8s \n", $1":"$2, $1, $2, $3, $4, $5 }'

docker images |awk -F "[ ]{2,}"  '{ printf "%32.32s    %16.16s    %16.16s    %8.8s \n", $1":"$2, $3, $4, $5 }'
