#! /bin/bash

EMACS_DIR=/home/core/data/emacs

if [ ! -f "$EMACS_DIR/root/.ssh/id_rsa" ]
then
	sudo mkdir -p $EMACS_DIR/root/.ssh
	sudo ssh-keygen -f $EMACS_DIR/root/.ssh/id_rsa -N '' -t rsa
	sudo cat $EMACS_DIR/root/.ssh/id_rsa.pub | update-ssh-keys -a core
	sudo echo 'StrictHostKeyChecking no' >> /home/core/.ssh/config
	sudo echo 'UserKnownHostsFile /dev/null' >> /home/core/.ssh/config
fi

echo "init ..."
docker stop emacs 2>/dev/null
echo "start ..."
docker rm emacs 2>/dev/null

docker run -d --name emacs -p 127.0.0.1:5858:22 -v $EMACS_DIR/root:/root -v $EMACS_DIR/root/.ssh/id_rsa.pub:/authorized_keys -v $EMACS_DIR:/root/.emacs.d -v /home/core/data:/data -v /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key ivories/emacs:1.0

sleep 3s

ssh -t -i $EMACS_DIR/root/.ssh/id_rsa root@localhost -p 5858 'e'

docker stop emacs && docker rm emacs &
