#!/bin/bash
source /home/core/.profile
ETH0=`/home/core/docker/shell/local_area_ip $1`

if [ $1 ]
then
  etcd2 --name `hostname` --initial-advertise-peer-urls http://$ETH0:2380 \
        --listen-peer-urls http://$ETH0:2380 \
        --listen-client-urls http://$ETH0:2379,http://127.0.0.1:2379 \
        --advertise-client-urls http://$ETH0:2379 \
        --discovery $DC_SERVER
fi

etcdFileName=/etc/systemd/system/etcd.service
etcd2FileName=/etc/systemd/system/etcd2.service
sudo rm -rf $etcd2FileName
sudo rm -rf /etc/systemd/system/multi-user.target.wants/etcd2.service

if [ ! $DC_SERVER ]
then
    exit 0
fi

sudo touch $etcd2FileName
sudo chmod -R 777 $etcd2FileName

sudo rm -rf /var/lib/etcd2/member

cat > $etcd2FileName << EOF
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/var/lib/etcd2
Environment=ETCD_NAME=`hostname`
Environment=ETCD_INITIAL_ADVERTISE_PEER_URLS=http://$ETH0:2380
Environment=ETCD_LISTEN_PEER_URLS=http://$ETH0:2380
Environment=ETCD_LISTEN_CLIENT_URLS=http://$ETH0:2379,http://127.0.0.1:2379 
Environment=ETCD_ADVERTISE_CLIENT_URLS=http://$ETH0:2379
#Environment=ETCD_DISCOVERY=$DC_SERVER
Environment=ETCD_INITIAL_CLUSTER=$DC_SERVER
Environment=ETCD_INITIAL_CLUSTER_STATE=new
Environment=ETCD_INITIAL_CLUSTER_TOKEN=$DC_TOKEN
ExecStart=/usr/bin/etcd2
Restart=always
RestartSec=10s
#LimitNOFILE=40000
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
EOF

sudo cp -rfp $etcd2FileName $etcdFileName

waitService etcd2
