#! /bin/bash
GLUSTER_INFO="/home/core/.glusterd.info"
if [ -f "$GLUSTER_INFO" ]
then
    echo "exists glusterd.info"
else
    data=`uuidgen`
    echo "UUID=$data" > $GLUSTER_INFO
    echo "operating-version=30800" >> $GLUSTER_INFO
fi
