#! /bin/bash

DIR_PATH="/home/core"
DIR_DATA="$DIR_PATH/data/"
DIR_DOCKER="$DIR_PATH/docker/"

mkdir $DIR_DATA

for SERVICE_NAME in redis mysql php nginx
do
    mkdir $SERVICE_NAME
    cp -rfp ${DIR_DOCKER}${SERVICE_NAME}/conf ${DIR_DATA}${SERVICE_NAME}/
done

sudo chown -R root:root $DIR_DATA
