#! /bin/bash

if [ $1 = ""]
then
    echo install_systemctl someservice
else
    mkdir -p /home/core/data/$1
    sudo cp -rfp /home/core/docker/$1/conf/* /home/core/data/$1/
    sudo cp -rfp /home/core/docker/service/$1.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable $1
    sudo systemctl start $1 &
fi
