#! /bin/bash

if [ $1 ]
then
    if [ -d "/home/core/docker/$1/conf/" ]
    then
        if [ -d "/home/core/data/$1/" ]
        then
            sudo mkdir -p /home/core/data/$1
            sudo cp -rfp /home/core/docker/$1/conf/* /home/core/data/$1/
        fi
    fi

    fs $1

else
    echo install_fleetctl someservice
fi
