#! /bin/bash

DIR_PATH="/home/core"
DIR_DATA="$DIR_PATH/data/"
DIR_DOCKER="$DIR_PATH/docker/"

sudo mkdir -p $DIR_DATA

sudo systemctl start etcd
sudo systemctl start fleet

#if vps
sudo dd if=/dev/zero of=/swap bs=1024 count=1024000
sudo mkswap /swap
sudo swapon /swap
sudo touch /etc/fstab
sudo chown -R core:core /etc/fstab
echo "swap                    /swap                   swap    defaults        0 0" >> /etc/fstab
#end if

sudo touch /etc/sysctl.conf
sudo chown -R core:core /etc/sysctl.conf
echo "vm.overcommit_memory = 1" >> /etc/sysctl.conf

for SERVICE_NAME in redis mysql php nginx www git ss5 samba
do
    sudo cp -rfp ${DIR_DOCKER}${SERVICE_NAME}/conf ${DIR_DATA}${SERVICE_NAME}/
    fleetctl destroy ${DIR_DOCKER}service/${SERVICE_NAME}
    fleetctl submit ${DIR_DOCKER}service/${SERVICE_NAME}
done

sudo chown -R root:root $DIR_DATA
