#!/bin/bash
p_by_name ivories/laravel 2>/dev/null
docker run -it --rm --net nginx-network -p 8000:8000 -p 8010:8010 -v /root/.ssh:/root/.ssh -v ~/laravel:/www -v ~/data/www/composer:/tmp -v ~/data:/data ivories/laravel
