#!/bin/bash
p_by_name ivories/laravel 2>/dev/null
docker run --name=laravel -it --rm --net=host -v /root/.ssh:/root/.ssh -v ~/data/www:/www -v ~/data:/data -v ~/data/www/composer:/tmp ivories/laravel zsh
