#! /bin/bash

#D:\nfs -rw -sync -no_root_squash -no_subtree_check -public -range 192.168.1.1 192.168.1.255
#D:\nfs -range 192.168.1.1 192.168.1.255

sudo touch /home/core/.profile
source /home/core/.profile

if [ ${MOUNT_I} ]
then
for ((i=0;i<$MOUNT_I;i++))
do
    if [ "${MOUNT_URL[i]}" != "" ]
    then
        if [ "${MOUNT_DIR[i]}" != "" ]
        then
            sudo mkdir -p ${MOUNT_DIR[i]}
            sudo mount -t nfs -o nolock,vers=3,tcp ${MOUNT_URL[i]} ${MOUNT_DIR[i]}
            echo " sudo mount -t nfs -o nolock,vers=3,tcp ${MOUNT_URL[i]} ${MOUNT_DIR[i]}"
        fi
    fi
done
fi
