#!/bin/bash
LOCAL_AREA_IP=`/home/core/docker/shell/local_area_ip`
/usr/bin/docker run --name mysql -p 127.0.0.1:3306:3306 -v /home/core/data/mysql:/etc/mysql -v /home/core/data/mysql/$LOCAL_AREA_IP:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=yellow --user=root ivories/mysql:1.0
