#!/bin/bash

if [ ! $1 ] 
then
    echo "s someservice" 
    exit
fi

fleetctl stop $1
fleetctl destroy $1

SERVICE_PATH="/home/core/data/$1/$1.service"

if [ $2 ]
then
    SERVICE_PATH="/home/core/docker/$1/$1.service"
fi

if [ ! -f "$SERVICE_PATH" ]
then
    sudo cp -rfp "/home/core/docker/$1/$1.service" "/home/core/data/$1/$1.service"
fi 

fleetctl submit $SERVICE_PATH

fleetctl start $1
