#! /bin/bash
#sudo rm -rf /home/core/.bashrc
#cp /home/core/docker/shell/bashrc /home/core/.bashrc
#sudo cp /home/core/docker/shell/bashrc /root/.bashrc

echo "export PATH=\"/home/core/docker/shell:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin:\$PATH\" > /home/core/.bashrc
echo "export PATH=\"/home/core/docker/shell:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin:\$PATH\" > /root/.bashrc

export PATH="/home/core/docker/shell:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin:$PATH"

