#!/bin/bash

if [ ! $1 ] 
then
    echo "ss someservice" 
    exit
fi

sudo systemctl stop $1

DATA_PATH="/home/core/data/$1/$1.service"
SERVICE_PATH="/home/core/docker/$1/$1.service"

if [ -f "$DATA_PATH" ]
then
    sudo cp -rfp "$DATA_PATH" "/etc/systemd/system/$1.service"
else
    sudo cp -rfp "$SERVICE_PATH" "/etc/systemd/system/$1.service"
fi 

sudo systemctl enable $1
sudo systemctl daemon-reload
sudo systemctl start $1
