#!/bin/bash

sudo systemctl start $1

for ((i=0; i<10; i++)); do

    isActive=`systemctl is-active $1`
    if [ $isActive == 'active' ]
    then
        sleep 1s
        sudo systemctl enable $1
        sudo systemctl daemon-reload
        echo "true"
        exit 0
    fi

    sleep 1s

done

sudo systemctl diable $1
echo "false"
