#! /bin/bash

if [ $1 ]
then
    echo "service use $1"
    cd ~/docker/service
else
    echo "service default local"
    cd ~/docker/service/local
fi

for SERVICE_NAME in redis mysql php nginx autorun
do
    fleetctl stop $SERVICE_NAME
    fleetctl destroy $SERVICE_NAME.service
    fleetctl submit $SERVICE_NAME.service
    fleetctl start $SERVICE_NAME &
done
