FROM  eosio/eos:v1.4.2

RUN apt-get -yqq  update \
#    &&apt-get -yqq install apt-utils \
    &&apt-get -yqq install net-tools

CMD [""]
#CMD ["/bin/bash","-c","keosd --http-server-address=0.0.0.0:5555 & exec nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false --filter-on='*'"]
