FROM lisnaz/omnicore

#USER root

#RUN chown -R root:root /app/omnicore
#RUN ln -sfn /home/omnicore/.bitcoin /root/.bitcoin

ENTRYPOINT [""]
CMD ["/app/omnicore/bin/omnicored"]
#CMD su - root -c "omnicored"
