FROM node:alpine

RUN apk add --no-cache python
RUN apk add --no-cache build-base
RUN apk add --no-cache libc-dev
RUN apk add --no-cache libusb-dev
RUN apk add --no-cache linux-headers
RUN apk add --no-cache eudev-dev
