FROM ubuntu:14.04

#FROM nvidia/cuda:8.0-cudnn5-runtime

RUN apt update
RUN apt-get install -y curl wget

#apt-get install nvidia-375
#RUN export CRYOSPARC_LICENSE_ID="" && mkdir -p $HOME/cryosparc && cd $HOME/cryosparc && export download_url=$(curl --silent -H "cryoSPARC-License: $CRYOSPARC_LICENSE_ID" "https://cryosparc.download/get/latest") && curl --silent "$download_url" > cryosparc.tar.gz && tar -zxvf cryosparc.tar.gz
#./install.sh --license-id=$CRYOSPARC_LICENSE_ID


