#!/bin/bash

/usr/local/bin/docker stop emacs_cargo 1>2 2>/dev/null
/usr/local/bin/docker rm emacs_cargo 1>2 2>/dev/null

/usr/local/bin/docker run --name emacs_cargo -it -e "TERM=xterm-256color" --net=host -e USER=root --user "root":"root" -v /home/core/data/rust/cargo:/root/.cargo -v "/home/core$PWD":/data/rust -w /data/rust ivories/rust cargo $*

/usr/local/bin/docker stop emacs_cargo 1>2 2>/dev/null
/usr/local/bin/docker rm emacs_cargo 1>2 2>/dev/null

