#!/bin/bash

/usr/local/bin/docker run --rm -it -e "TERM=xterm-256color" -e USER=root --user "root":"root" -v /root/.cargo:/root/.cargo -v "/home/core$PWD":/data/rust -w /data/rust ivories/rust cargo $*
